Improvements to apply branch
fabianvf/openshift-restclient-python pull request #2
Opened 2018-11-22 08:45 UTC by willthames

2018-11-22 08:48 UTC, willthames commented
This is working much better now, but very much still a WIP - this isn't handling lists any better than before!

By adding test cases here and at https://github.com/ansible/ansible/commit/01913d24637ad1de715ccd394cdccc4c10858b9d at least it's easy to see what to work on next (lists that have default parameters added!)

2018-12-13 10:42 UTC, willthames commented
@fabianvf I've done a complete test run with my ansiblefest2018, found another bug, but this all seems good to me. Do you want to tidy up the loose ends of moving the logic into client.py?

2018-12-13 15:00 UTC, fabianvf commented
@willthames nice work, that would be awesome!

2018-12-17 19:46 UTC, fabianvf commented
@willthames, sorry, this repo isn't on my normal watchlist so I totally forgot about it

2018-12-17 20:00 UTC, fabianvf requested changes
a few things I noticed, but definitely looks better. Name changes make it way easier to follow and a big +1 for tests

2018-12-17 20:00 UTC, fabianvf commented on openshift/dynamic/apply.py
> +                                  namespace=definition['metadata']['namespace'],
Namespace may not be defined, in the case of a cluster-level resource.

2018-12-17 20:00 UTC, fabianvf commented on openshift/dynamic/apply.py
> +            patch[k] = desired_value
For computing deletions I think we leave this out

2018-12-17 20:00 UTC, fabianvf commented on openshift/dynamic/apply.py
> +            patch[k] = desired_value
We should leave this out as well, we only want to get deletions (things that have not been explicitly removed will not be changed by the patch)

2018-12-17 20:00 UTC, fabianvf commented on openshift/dynamic/apply.py
> -        else:
I think we need this else block, right?

2018-12-17 20:00 UTC, fabianvf commented on openshift/dynamic/apply.py
> +def dict_merge(a, b):
I think we can avoid doing a complex merge here, since deletions + delta should be non-intersecting sets of changes.

2018-12-17 20:01 UTC, fabianvf commented
@willthames let me know if you want me to just go ahead and merge this and reraise the comments on the osrcp PR

2018-12-17 23:18 UTC, willthames commented
@fabianvf yeah, merge this and we'll address issues in the other PR

I agree with your namespace comment, but I'm going to need failing test cases for the rest. At the moment the situation is that the tests pass

2018-12-17 23:20 UTC, willthames commented on openshift/dynamic/apply.py
> +def dict_merge(a, b):
I'm pretty sure this isn't true, because I put this in to get past a failure (I wouldn't have bothered otherwise). I just can't remember the exact details.

Feel free to swap it out and run the test suite (both here and at the ansible end) to see where it goes awry!

2018-12-17 23:22 UTC, willthames commented on openshift/dynamic/apply.py
> +                                  namespace=definition['metadata']['namespace'],
Hmm, I know I had to put in a namespace fix for something else - it might be that I've never patched something without a namespace. This is an excellent test suite candidate.

2018-12-18 00:03 UTC, fabianvf commented on openshift/dynamic/apply.py
> +def dict_merge(a, b):
Hmm, if we're seeing conflicting changes we may have the algorithm wrong, let me dig into the go code a little more and see if I misunderstood

2018-12-18 00:04 UTC, merged

2019-01-14 22:09 UTC, willthames commented on openshift/dynamic/apply.py
> +def dict_merge(a, b):
The failing test case is replacing a dict item

```
data:
  one: "1"
  two: "2"
```

to 

```
data:
   one: "1"
   three: "3"
```

This should result in 

```
data: 
   two: None
   three: "3"
```

without the `dict_merge`, data['two'] gets replaced by data['three']